[package]
name = "invaders"
version = "0.1.0"
authors = ["Les Orchard <me@lmorchard.com>"]
build = "build.rs"

[dependencies]
ggez = "0.4"
specs = "0.10"
# specs = { git = "https://github.com/slide-rs/specs.git" }
specs-derive = "0.1.0"
maplit = "1.0.1"
rand = "0.3.14"
rayon = "0.9"
