[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "TRAVIS",
    "PKG_CONFIG_ALLOW_CROSS",
]

[target.i686-unknown-linux-gnu]
image = "lmorchard/ggez-i686-unknown-linux-gnu:latest"

[target.x86_64-unknown-linux-gnu]
image = "lmorchard/ggez-x86_64-unknown-linux-gnu:latest"
